// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: src/popupservice/popup.proto

package popup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PopupService_GetPopupMessage_FullMethodName = "/popup.PopupService/GetPopupMessage"
)

// PopupServiceClient is the client API for PopupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PopupServiceClient interface {
	GetPopupMessage(ctx context.Context, in *PopupRequest, opts ...grpc.CallOption) (*PopupReply, error)
}

type popupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPopupServiceClient(cc grpc.ClientConnInterface) PopupServiceClient {
	return &popupServiceClient{cc}
}

func (c *popupServiceClient) GetPopupMessage(ctx context.Context, in *PopupRequest, opts ...grpc.CallOption) (*PopupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopupReply)
	err := c.cc.Invoke(ctx, PopupService_GetPopupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PopupServiceServer is the server API for PopupService service.
// All implementations must embed UnimplementedPopupServiceServer
// for forward compatibility.
type PopupServiceServer interface {
	GetPopupMessage(context.Context, *PopupRequest) (*PopupReply, error)
	mustEmbedUnimplementedPopupServiceServer()
}

// UnimplementedPopupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPopupServiceServer struct{}

func (UnimplementedPopupServiceServer) GetPopupMessage(context.Context, *PopupRequest) (*PopupReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopupMessage not implemented")
}
func (UnimplementedPopupServiceServer) mustEmbedUnimplementedPopupServiceServer() {}
func (UnimplementedPopupServiceServer) testEmbeddedByValue()                      {}

// UnsafePopupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PopupServiceServer will
// result in compilation errors.
type UnsafePopupServiceServer interface {
	mustEmbedUnimplementedPopupServiceServer()
}

func RegisterPopupServiceServer(s grpc.ServiceRegistrar, srv PopupServiceServer) {
	// If the following call panics, it indicates UnimplementedPopupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PopupService_ServiceDesc, srv)
}

func _PopupService_GetPopupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopupServiceServer).GetPopupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PopupService_GetPopupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopupServiceServer).GetPopupMessage(ctx, req.(*PopupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PopupService_ServiceDesc is the grpc.ServiceDesc for PopupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PopupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "popup.PopupService",
	HandlerType: (*PopupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopupMessage",
			Handler:    _PopupService_GetPopupMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/popupservice/popup.proto",
}
