// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: src/popupservice/popup.proto

package popup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopupRequest) Reset() {
	*x = PopupRequest{}
	mi := &file_src_popupservice_popup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopupRequest) ProtoMessage() {}

func (x *PopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_popupservice_popup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopupRequest.ProtoReflect.Descriptor instead.
func (*PopupRequest) Descriptor() ([]byte, []int) {
	return file_src_popupservice_popup_proto_rawDescGZIP(), []int{0}
}

func (x *PopupRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PopupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopupReply) Reset() {
	*x = PopupReply{}
	mi := &file_src_popupservice_popup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopupReply) ProtoMessage() {}

func (x *PopupReply) ProtoReflect() protoreflect.Message {
	mi := &file_src_popupservice_popup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopupReply.ProtoReflect.Descriptor instead.
func (*PopupReply) Descriptor() ([]byte, []int) {
	return file_src_popupservice_popup_proto_rawDescGZIP(), []int{1}
}

func (x *PopupReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_popupservice_popup_proto protoreflect.FileDescriptor

const file_src_popupservice_popup_proto_rawDesc = "" +
	"\n" +
	"\x1csrc/popupservice/popup.proto\x12\x05popup\"-\n" +
	"\fPopupRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"&\n" +
	"\n" +
	"PopupReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2K\n" +
	"\fPopupService\x12;\n" +
	"\x0fGetPopupMessage\x12\x13.popup.PopupRequest\x1a\x11.popup.PopupReply\"\x00B/Z-github.com/your/module/src/popupservice;popupb\x06proto3"

var (
	file_src_popupservice_popup_proto_rawDescOnce sync.Once
	file_src_popupservice_popup_proto_rawDescData []byte
)

func file_src_popupservice_popup_proto_rawDescGZIP() []byte {
	file_src_popupservice_popup_proto_rawDescOnce.Do(func() {
		file_src_popupservice_popup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_popupservice_popup_proto_rawDesc), len(file_src_popupservice_popup_proto_rawDesc)))
	})
	return file_src_popupservice_popup_proto_rawDescData
}

var file_src_popupservice_popup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_popupservice_popup_proto_goTypes = []any{
	(*PopupRequest)(nil), // 0: popup.PopupRequest
	(*PopupReply)(nil),   // 1: popup.PopupReply
}
var file_src_popupservice_popup_proto_depIdxs = []int32{
	0, // 0: popup.PopupService.GetPopupMessage:input_type -> popup.PopupRequest
	1, // 1: popup.PopupService.GetPopupMessage:output_type -> popup.PopupReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_popupservice_popup_proto_init() }
func file_src_popupservice_popup_proto_init() {
	if File_src_popupservice_popup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_popupservice_popup_proto_rawDesc), len(file_src_popupservice_popup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_popupservice_popup_proto_goTypes,
		DependencyIndexes: file_src_popupservice_popup_proto_depIdxs,
		MessageInfos:      file_src_popupservice_popup_proto_msgTypes,
	}.Build()
	File_src_popupservice_popup_proto = out.File
	file_src_popupservice_popup_proto_goTypes = nil
	file_src_popupservice_popup_proto_depIdxs = nil
}
